import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'integrador-app';
}



/** DEPENDENCIAS/LIBRERIAS
 SPRING WEB  : INCLUYE EL API Y LAS ANOTACIONES PARA CREAR LOS CONTROLADORES RESTFULL , UTILIZANDO LA ANOTACION RESTCONTROLLER
 Y EL CONTROLADOR SE COMUNICA CON LA CLASE DEL MODELO, EL SERVICE ,ETC , LOS DATOS SE ENVIAN AL CONTROLADOR Y SE RETORNAN EN UNA ESTRUCTURA JSON
 SQL /  JPA :   YA QUE SE VA A TRABAJAR CON EL API DE PERSISTENCIA DE JAVA ATRAVES DE HIBERNATE Y CON LAS CLASES ENTITY QUE ESTAN MAPEADAS
 A TABLAS DE LA BASE DE DATOS
 MYSQL : MOTOR DE BASE DE DATOS


 PONXML VA TODA LA ESTRUCTURA Y EL ESQUELETO DEL PROYECTO  */
